[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"
authors = ["Luka Prebil Grintal <luka.p.grintal@1337.tech>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_of_code_traits = "0.2.0"